=== NCEAS/mdqengine/src/main/resources/schemas/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://nceas.ucsb.edu/mdqe" targetNamespace="https://nceas.ucsb.edu/mdqe" version="1.0">

  <xs:element name="check" type="tns:check"/>

  <xs:element name="run" type="tns:run"/>

  <xs:element name="suite" type="tns:suite"/>

  <xs:complexType name="check">
<xs:annotation>
<xs:documentation><![CDATA[Checks do the heavy lifting of QC checking. The general idea is that they are fed one or more 
values from the document being QCed - using Selectors - and then run some code on those value[s].

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the check. The id can be used to reference previously defined checks
within the same MDQ engine store. This is useful for common checks that should be shared 
across Suites]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The short, but useful, name of the check. This will typically be how we colloquially refer to the check.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="description" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The longer more detailed explanation of what the check is doing. This might even include pseudo code or a summary of
the actions performed by the Check.code]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="type" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The type is meant to categorize the check. While we have not defined a vocabulary for check types, we envision some examples as:
metadata, data, congruency. Currently, check writers are able to use any string they desire.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="level" type="tns:level">
<xs:annotation>
<xs:documentation><![CDATA[The level indicates how important this check is and must pull from the controlled Level vocabulary (INFO, OPTIONAL, REQUIRED).
The level will help us better summarize the check results. For example, a REQUIRED check that fails is more severe than an INFO check
that fails.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="environment" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The environment specifies what language the check code should be dispatched to. The environment, code and library elements should all 
agree so that syntax and dependencies can be appropriately met. This field is case-insensitive.
Current options include: 
'r' (the Renjin engine), 
'rscript' (RScript command line), 
'JavaScript' (the JavaScript engine)
'python' (the Jython engine)
'Java' (Java class implementations of Callable<Result>)]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="code" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The for scripted environments (not 'Java') this is the code to be executed. When Check.environment is 'Java' this will be the fully qualified class 
name of the Callable<Result> implementation.
The script code can take a few different forms, but should minimally return some value that will be captured as a single Result.output.
The simplest form is just a series of script statements with the final statement returning the desired value for Result.output.
Alternatively, a call() function can be defined that returns the desired Result.output. This function will be called automatically if no output is found when executing the
script as a series of statements.
If both output and status need to be returned, the code can set 'output' and 'status' variables and those will be included in the Result.
Finally - for greatest control - a full instance of the Result class can be returned in which case the code writer is responsible for setting the appropriate Result fields in a 
variable named 'mdq_result'.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="library" type="xs:anyURI">
<xs:annotation>
<xs:documentation><![CDATA[One or more external script libraries can be included using their URL. Caution should be taken that these URLs are trusted so that 
malicious code cannot be executed by the engine.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="inheritState" type="xs:boolean">
<xs:annotation>
<xs:documentation><![CDATA[Be default, each check is entirely independent and does not share the script environment of any previously executed checks in the Suite.
If checks need to reference variables or functions defined in earlier checks within the same suite, they can set this flag to 'true'.
Care should be taken when inheriting state such that variable name collisions do not cause unintended results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="selector" type="tns:selector">
<xs:annotation>
<xs:documentation><![CDATA[Selectors are used to extract certain parts of the metadata document and make those values available to the Check.code.
Each selector should have a unique name within the same check since the Selector.name is used to create a global variable in the
scripting environment. The code can then reference that variable name (exactly!) and gain access to the value (if it exists).
The variables can be strings, numbers, booleans and lists of those types. When a selector does locate a value in the 
document, a null value (however that is represented in the particular script environment) will be provided.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="dialect" type="tns:dialect">
<xs:annotation>
<xs:documentation><![CDATA[The optional dialect list can be used to identify checks as only pertaining to specific metadata types.
Instead of constraining this to a pre-determined list of dialects, they are self-defined by Dialect.xpath 
such that a dialect can use any xpath expression to determine if a document is indeed that dialect.
Typically, we will use namespace comparisons, but there is technically no limit of how a dialect can determine 
what it is.
If a document is in the dialect list, the check will not be run and Result.status will be set to Status.SKIP.
If no Dialect[s] are provided, it is assumed that the check applies to any and all metadata documents.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="selector">
<xs:annotation>
<xs:documentation><![CDATA[Selectors are used to extract value[s] from metadata documents using XPath expressions.

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The selector name is used to create a variable in the environment specified by
Check.environment and should be a valid variable for that target environment.
reserved tokens like 'var', 'int', 'public', etc.. should be avoided.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="xpath" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The xpath expression use to extract value[s] from the document for this named 
selector.
The xpath will often be a compound expression to cover a variety of metadata dialects.
For example, the notion of a "title" can be stored in many different ways depending 
on the metadata standard used, but conceptually the value can be checked exactly the same
no matter where or how it is serialized in metadata.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="subSelector" type="tns:selector">
<xs:annotation>
<xs:documentation><![CDATA[Subselectors can be used when access to complex structures is required and the structure needs to be 
preserved. Often is is used to return lists of lists (e.g., when examining attributes of multiple entities).]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="namespaces">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="namespace" nillable="true" type="tns:namespace"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="namespace">
<xs:annotation>
<xs:documentation><![CDATA[The namespace maps a full uri to a prefix.

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="prefix" type="xs:string" use="required">
<xs:annotation>
<xs:documentation><![CDATA[The namespace prefix. This should match the prefix used in XPath expression[s]]]></xs:documentation>
</xs:annotation>
</xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dialect">
    <xs:sequence>
      <xs:element minOccurs="0" name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The name or label to associate with this dialect definition]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="xpath" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The XPath expression that is used to determine if a document is of this dialect.
The expression should evaluate to a boolean value, where true indicates the document 
is of this dialect.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="metadata">
<xs:annotation>
<xs:documentation><![CDATA[Captures additional information about the document being QCed.
Intended to be used in conjunction with a Run  to more easily 
analyze the results

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="dataUrl" type="xs:string"/>
      <xs:element minOccurs="0" name="datasource" type="xs:string"/>
      <xs:element minOccurs="0" name="formatId" type="xs:string"/>
      <xs:element minOccurs="0" name="funder" type="xs:string"/>
      <xs:element minOccurs="0" name="rightsHolder" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="output">
<xs:annotation>
<xs:documentation><![CDATA[The output of check code is captured as Output. Many kinds of output are allowed:
Scalar values( e.g., message strings, numbers, booleans)
Complex structures serialized as strings (e.g., lists, tabular data, JSON)
Base64 encoded binary data (e.g., png images)
The type attribute should be used to indicate the kind of output value

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The type of output value. If omitted, a scalar string value will be assumed.
Standard MIME-types should be used if including binary base64 encoded data.]]></xs:documentation>
</xs:annotation>
</xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="result">
    <xs:sequence>
      <xs:element minOccurs="0" name="check" type="tns:check">
<xs:annotation>
<xs:documentation><![CDATA[The check that was run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="timestamp" type="xs:dateTime">
<xs:annotation>
<xs:documentation><![CDATA[The timestamp of the check execution]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="output" nillable="true" type="tns:output">
<xs:annotation>
<xs:documentation><![CDATA[The list of output value[s] from the check execution]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="status" type="tns:status">
<xs:annotation>
<xs:documentation><![CDATA[The status of the check run, constrained to the Status enum]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="run">
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the QC run. This will likely be long and opaque
(like a UUID) considering the quantity of runs that will likely be performed 
over the content in a large repository.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="timestamp" type="xs:dateTime">
<xs:annotation>
<xs:documentation><![CDATA[The timestamp of the QC run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="objectIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The identifier of the metadata document that was QCed.
This is optional since in some cases, we will be performing 
QC on objects that are being actively edited/created and 
do not yet exist with persistent identifiers.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="metadata" type="tns:metadata">
<xs:annotation>
<xs:documentation><![CDATA[Additional information about the document that was QCed.
This can be helpful when analyzing and aggregating batches of run results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="suiteId" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The identifier for the suite that was run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="result" type="tns:result">
<xs:annotation>
<xs:documentation><![CDATA[The list of results for this run. Results contain the check that was run and 
the outcome of the check.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="suite">
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the suite. This should be unique, at the very least, 
within the scope of the MDQ engine store. It will be used to identify which
suite[s] to run on metadata documents and for organizing QC results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[A short and useful name for the suite that will be displayed in 
user interfaces and reports.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="description" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[A comprehensive sumary of the suite and what it is intended to check.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" name="check" type="tns:check">
<xs:annotation>
<xs:documentation><![CDATA[The list of checks to be performed. A suite must have at least one check.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="level">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="OPTIONAL"/>
      <xs:enumeration value="REQUIRED"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="SUCCESS"/>
      <xs:enumeration value="FAILURE"/>
      <xs:enumeration value="SKIP"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== NCEAS/mdqengine/src/main/resources/checks/lookup.award.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 ../schemas/schema1.xsd">
	<id>check.lookup.award.1</id>
	<name>Award lookup</name>
	<description>Look up award information from NSF using award ID.</description>
	<type>identification</type>
	<level>INFO</level>
	<environment>Java</environment>
	<code>edu.ucsb.nceas.mdqengine.processor.AwardLookupCheck</code>
	<!-- not used -->
	<selector>
		<name>awards</name>
		<xpath>/eml/dataset/project/funding//para</xpath>
	</selector>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/usage.is.cc.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
  <id>check.usage.is.cc.1</id>
  <name>Usage</name>
  <description>Usage should be Creative Commons</description>
  <type>identification</type>
  <level>REQUIRED</level>
  <environment>rscript</environment>
  <code><![CDATA[
library(stringr)

phrases <- c("This work is licensed under the Creative Commons Attribution 4.0 International License.\nTo view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.",
             "This work is dedicated to the public domain under the Creative Commons Universal 1.0 Public Domain Dedication.\nTo view a copy of this dedication, visit https://creativecommons.org/publicdomain/zero/1.0/.")

if (length(rights) == 0) {
  status <- "FAILURE"
  message <- "The document is not explicitly licensed with a Creative Commons CC-0 or CC-BY license."
} else if (length(rights) > 1) {
  status <- "FAILURE"
  message <- "More than one license was found which was an unexpected state."
} else {
  if (any(str_detect(rights[[1]], phrases))) {
    status <- "SUCCESS"
    message <- "The document is explicitly licensed with a Creative Commons CC-0 or CC-BY license."
  } else {
    status <- "FAILURE"
    message <- "The document is not explicitly licensed with a Creative Commons CC-0 or CC-BY license."
  }
}

mdq_result <- list(status = status,
                   output = list(list(value = message)))
  ]]></code>
  <selector>
    <name>rights</name>
    <xpath>/eml/dataset/intellectualRights/para</xpath>
  </selector>
  <dialect>
    <name>eml</name>
    <xpath>boolean(/*[local-name() = 'eml'])</xpath>
  </dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/creator.has.orcid.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
	<id>check.creator.has.orcid.1</id>
	<name>Creator has ORCID</name>
	<description>The creator field should contain an ORCID, email and address.</description>
	<type>identification</type>  
	<level>INFO</level>
	<environment>rscript</environment>
	<code><![CDATA[
check <- function() {
  library(base)
  # These variables are defined by the MQE from the <xpath> selectors.
  # "creatorPresent" - the dataset creator
  # "userId"         - the dataset creator/userId
  # "emailPresent"   - the creator email
  # "addressPresent" - the creator address
  if(!creatorPresent) {
    return(list(status="SKIP", output="The 'creator' element is not present, can not check for an ORCID, electronicMailAddress or address."))
  }
  
  # There could be multiple creators, but just one creator with a 'userId' will satisfy this check
  if(is.null(userId)) {
    # Should this be a SKIP?
    return(list(status="FAILURE", output="The 'creator/userId' element not present, can not check for an ORCID"))
  }
  
  hasORCID <- grepl("^\\s*http://orcid.org", userId, perl=T) || grepl("^\\s*ORCID", userId, perl=T)
  if(!hasORCID) {
    return(list(status="FAILURE", output="The 'creator/userId' element does not contains an ORCID"))
  }
  
  # There could be multiple creators, but just one creator with an 'email' will satisfy this check
  if(!emailPresent) {
    return(list(status="FAILURE", output="The 'creator/electronicMailAddress' element is not present"))
  } 
  
  # There could be multiple creators, but just one creator with an 'address' will satisfy this check
  if(!addressPresent) {
    return(list(status="FAILURE", output="The 'creator/address' element is not present"))
  } 
  
  return(list(status="SUCCESS", output="The 'creator' element has a 'userId' ORCID, 'electronicMailAddress' and 'address' elements"))
}

result <- check()
mdq_result <- list(status=result$status, output=list(list(value=result$output))) 
]]></code>
  <selector>
		 <name>creatorPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/creator)</xpath>
	 </selector>
  <selector>
		 <name>userId</name>
		 <xpath>/*[local-name() = 'eml']/dataset/creator/userId</xpath>
	 </selector>
  <selector>
		 <name>emailPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/creator/electronicMailAddress)</xpath>
	 </selector>
  <selector>
		 <name>addressPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/creator/address)</xpath>
	 </selector>
	 <dialect>
		 <name>eml</name>
		 <xpath>boolean(/*[local-name() = 'eml'])</xpath>
	 </dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/coverage.in.arctic.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 ../schemas/schema1.xsd">
  <id>coverage.in.arctic.1</id>
  <name>Arctic coverage</name>
  <description>At least one geographic coverage should intersect with the Arctic, which is defined as the area north of 45Â° N latitude.</description>
  <type>interpretation</type>
  <level>INFO</level>
  <environment>rscript</environment>
  <code><![CDATA[
  library(metadig)

  if (any(na.omit(as.numeric(north_bound_coordinates)) >= 45)) {
    if (any(na.omit(as.numeric(north_bound_coordinates)) > 90)) {
      failure("A north bounding coordinate is out of range. The valid range is 0 to +90.")
    } else {
      success("At least one geographic coverage is in the Arctic.")
    }
  } else {
    failure("No geographic coverage is in the Arctic.")
  }
  ]]></code>
  <selector>
    <name>north_bound_coordinates</name>
    <xpath>//coverage//geographicCoverage/boundingCoordinates/northBoundingCoordinate</xpath>
  </selector>
</mdq:check>

=== NCEAS/mdqengine/src/test/resources/test-docs/test-suite.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:suite xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 /Users/leinfelder/git/mdqengine/src/main/resources/schemas/schema1.xsd">
	<id>suite.2.1</id>      
	<name>Testing suite</name>
   <check>
      <id>check.1.1</id>      
      <name>Title Length</name>
      <description>Checks that title is longer than 10 characters</description>
      <type>metadata</type>
      <level>OPTIONAL</level>
      <environment>r</environment>
      <code><![CDATA[nchar(title) > 10]]></code>      
      <selector>
         <name>title</name>
         <xpath>//dataset/title</xpath>
      </selector>
   </check>
   <check>
      <id>check.2.1</id>
      <name>Entity Count</name>
      <description>Checks that there are 1 or more data entities in the data package</description>
      <type>data</type>      
      <level>INFO</level>
      <environment>JavaScript</environment>
      <code><![CDATA[entityCount > 0]]></code>
      <selector>
         <name>entityCount</name>
         <xpath>count(//dataset/dataTable | //dataset/otherEntity)</xpath>
      </selector>
   </check>
   <check>
      <id>check.3.1</id>  
      <name>Unique attribute names</name>
      <description>Checks that all attribute names are unique across datapackage</description>
      <level>REQUIRED</level>
      <environment>r</environment>
      <code><![CDATA[any(duplicated(attributeNames))]]></code>
      <selector>
         <name>attributeNames</name>
         <xpath>//attribute/attributeName</xpath>
      </selector>
   </check>
</mdq:suite>

=== NCEAS/mdqengine/src/main/resources/checks/entity.present.check.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 ../schemas/schema1.xsd">
	<id>check.entity.present.1</id>
	<name>Data entity</name>
	<description>At least one data entity should be present.</description>
	<type>interpretation</type>
	<level>OPTIONAL</level>
	<environment>rscript</environment>
	<code><![CDATA[
  library(metadig)

  check <- function() {
    # The variables defined by MQE from the <xpath> selectors.
    # "entityPresent" - is a data entity present?

    # Assume that the check will succeed, until proven otherwise
    status <- "SUCCESS"
    # The output messages will be gathered into a list
    outputList <- list()

    # The dataset may have multiple entities, so check each one.
    if (entityPresent) {
      if (entityCount == 1) {
        outputList[[length(outputList) + 1]] <- list(value = "One data description is present.")
      } else {
        outputList[[length(outputList) + 1]] <- list(value = sprintf("%d data descriptions are present.", entityCount))
      }
      return(list(status = status,
                  values = outputList))
    } else {
      outputList[[length(outputList) + 1]] <- list(value = "No data descriptions are present.")
      return(list(status = "FAILURE",
                  values = outputList))
    }
  }

  result <- check()

  mdq_result <- list(status = result$status,
                     output = result$values)
  ]]></code>
	<selector>
		<name>entityPresent</name>
		<xpath>boolean(/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity])</xpath>
	</selector>
	<selector>
		<name>entityCount</name>
		<xpath>count(/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity])</xpath>
	</selector>
	<dialect>
		<name>eml</name>
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/abstract.100.words.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
  <id>check.abstract.100.words.1</id>
  <name>Abstract length</name>
  <description>Abstract should be at least 100 words long.</description>
  <type>discovery</type>  
  <level>REQUIRED</level>
  <environment>rscript</environment>
  <code><![CDATA[
    if (length(abstract) == 0) {
      status <- "FAILURE"
      message <- "No abstract sections were found."
    } else if (length(abstract) > 1) {
      status <- "FAILURE"
      message <- "More than one abstract section was found when one was expected."
    } else {
      library(stringr)
      tokens <- str_split(abstract, " ")[[1]]

      if (length(tokens) >= 100) {
        status <- "SUCCESS"
        message <- paste0("The abstract was ", length(tokens), " word(s) long which is sufficient.")
      } else {
        status <- "FAILURE"
        message <- paste0("The abstract was only ", length(tokens), " word(s) long but 100 or more was requried.")
      }
    }

    mdq_result <- list(status = status,
                       output = list(list(value = message)))
  ]]></code>
  <selector>
    <name>abstract</name>
    <xpath>/eml/dataset/abstract</xpath>
  </selector>
  <dialect>
    <name>eml</name>
    <xpath>boolean(/*[local-name() = 'eml'])</xpath>
  </dialect>
</mdq:check>
