=== NCEAS/mdqengine/src/main/resources/schemas/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://nceas.ucsb.edu/mdqe" targetNamespace="https://nceas.ucsb.edu/mdqe" version="1.0">

  <xs:element name="check" type="tns:check"/>

  <xs:element name="run" type="tns:run"/>

  <xs:element name="suite" type="tns:suite"/>

  <xs:complexType name="check">
<xs:annotation>
<xs:documentation><![CDATA[Checks do the heavy lifting of QC checking. The general idea is that they are fed one or more 
values from the document being QCed - using Selectors - and then run some code on those value[s].

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the check. The id can be used to reference previously defined checks
within the same MDQ engine store. This is useful for common checks that should be shared 
across Suites]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The short, but useful, name of the check. This will typically be how we colloquially refer to the check.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="description" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The longer more detailed explanation of what the check is doing. This might even include pseudo code or a summary of
the actions performed by the Check.code]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="type" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The type is meant to categorize the check. While we have not defined a vocabulary for check types, we envision some examples as:
metadata, data, congruency. Currently, check writers are able to use any string they desire.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="level" type="tns:level">
<xs:annotation>
<xs:documentation><![CDATA[The level indicates how important this check is and must pull from the controlled Level vocabulary (INFO, OPTIONAL, REQUIRED).
The level will help us better summarize the check results. For example, a REQUIRED check that fails is more severe than an INFO check
that fails.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="environment" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The environment specifies what language the check code should be dispatched to. The environment, code and library elements should all 
agree so that syntax and dependencies can be appropriately met. This field is case-insensitive.
Current options include: 
'r' (the Renjin engine), 
'rscript' (RScript command line), 
'JavaScript' (the JavaScript engine)
'python' (the Jython engine)
'Java' (Java class implementations of Callable<Result>)]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="code" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The for scripted environments (not 'Java') this is the code to be executed. When Check.environment is 'Java' this will be the fully qualified class 
name of the Callable<Result> implementation.
The script code can take a few different forms, but should minimally return some value that will be captured as a single Result.output.
The simplest form is just a series of script statements with the final statement returning the desired value for Result.output.
Alternatively, a call() function can be defined that returns the desired Result.output. This function will be called automatically if no output is found when executing the
script as a series of statements.
If both output and status need to be returned, the code can set 'output' and 'status' variables and those will be included in the Result.
Finally - for greatest control - a full instance of the Result class can be returned in which case the code writer is responsible for setting the appropriate Result fields in a 
variable named 'mdq_result'.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="library" type="xs:anyURI">
<xs:annotation>
<xs:documentation><![CDATA[One or more external script libraries can be included using their URL. Caution should be taken that these URLs are trusted so that 
malicious code cannot be executed by the engine.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="inheritState" type="xs:boolean">
<xs:annotation>
<xs:documentation><![CDATA[Be default, each check is entirely independent and does not share the script environment of any previously executed checks in the Suite.
If checks need to reference variables or functions defined in earlier checks within the same suite, they can set this flag to 'true'.
Care should be taken when inheriting state such that variable name collisions do not cause unintended results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="selector" type="tns:selector">
<xs:annotation>
<xs:documentation><![CDATA[Selectors are used to extract certain parts of the metadata document and make those values available to the Check.code.
Each selector should have a unique name within the same check since the Selector.name is used to create a global variable in the
scripting environment. The code can then reference that variable name (exactly!) and gain access to the value (if it exists).
The variables can be strings, numbers, booleans and lists of those types. When a selector does locate a value in the 
document, a null value (however that is represented in the particular script environment) will be provided.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="dialect" type="tns:dialect">
<xs:annotation>
<xs:documentation><![CDATA[The optional dialect list can be used to identify checks as only pertaining to specific metadata types.
Instead of constraining this to a pre-determined list of dialects, they are self-defined by Dialect.xpath 
such that a dialect can use any xpath expression to determine if a document is indeed that dialect.
Typically, we will use namespace comparisons, but there is technically no limit of how a dialect can determine 
what it is.
If a document is in the dialect list, the check will not be run and Result.status will be set to Status.SKIP.
If no Dialect[s] are provided, it is assumed that the check applies to any and all metadata documents.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="selector">
<xs:annotation>
<xs:documentation><![CDATA[Selectors are used to extract value[s] from metadata documents using XPath expressions.

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The selector name is used to create a variable in the environment specified by
Check.environment and should be a valid variable for that target environment.
reserved tokens like 'var', 'int', 'public', etc.. should be avoided.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="xpath" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The xpath expression use to extract value[s] from the document for this named 
selector.
The xpath will often be a compound expression to cover a variety of metadata dialects.
For example, the notion of a "title" can be stored in many different ways depending 
on the metadata standard used, but conceptually the value can be checked exactly the same
no matter where or how it is serialized in metadata.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="subSelector" type="tns:selector">
<xs:annotation>
<xs:documentation><![CDATA[Subselectors can be used when access to complex structures is required and the structure needs to be 
preserved. Often is is used to return lists of lists (e.g., when examining attributes of multiple entities).]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="namespaces">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="namespace" nillable="true" type="tns:namespace"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="namespace">
<xs:annotation>
<xs:documentation><![CDATA[The namespace maps a full uri to a prefix.

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="prefix" type="xs:string" use="required">
<xs:annotation>
<xs:documentation><![CDATA[The namespace prefix. This should match the prefix used in XPath expression[s]]]></xs:documentation>
</xs:annotation>
</xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dialect">
    <xs:sequence>
      <xs:element minOccurs="0" name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The name or label to associate with this dialect definition]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="xpath" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The XPath expression that is used to determine if a document is of this dialect.
The expression should evaluate to a boolean value, where true indicates the document 
is of this dialect.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="metadata">
<xs:annotation>
<xs:documentation><![CDATA[Captures additional information about the document being QCed.
Intended to be used in conjunction with a Run  to more easily 
analyze the results

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="dataUrl" type="xs:string"/>
      <xs:element minOccurs="0" name="datasource" type="xs:string"/>
      <xs:element minOccurs="0" name="formatId" type="xs:string"/>
      <xs:element minOccurs="0" name="funder" type="xs:string"/>
      <xs:element minOccurs="0" name="rightsHolder" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="output">
<xs:annotation>
<xs:documentation><![CDATA[The output of check code is captured as Output. Many kinds of output are allowed:
Scalar values( e.g., message strings, numbers, booleans)
Complex structures serialized as strings (e.g., lists, tabular data, JSON)
Base64 encoded binary data (e.g., png images)
The type attribute should be used to indicate the kind of output value

(author): leinfelder]]></xs:documentation>
</xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The type of output value. If omitted, a scalar string value will be assumed.
Standard MIME-types should be used if including binary base64 encoded data.]]></xs:documentation>
</xs:annotation>
</xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="result">
    <xs:sequence>
      <xs:element minOccurs="0" name="check" type="tns:check">
<xs:annotation>
<xs:documentation><![CDATA[The check that was run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="timestamp" type="xs:dateTime">
<xs:annotation>
<xs:documentation><![CDATA[The timestamp of the check execution]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="output" nillable="true" type="tns:output">
<xs:annotation>
<xs:documentation><![CDATA[The list of output value[s] from the check execution]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="status" type="tns:status">
<xs:annotation>
<xs:documentation><![CDATA[The status of the check run, constrained to the Status enum]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="run">
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the QC run. This will likely be long and opaque
(like a UUID) considering the quantity of runs that will likely be performed 
over the content in a large repository.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="timestamp" type="xs:dateTime">
<xs:annotation>
<xs:documentation><![CDATA[The timestamp of the QC run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="objectIdentifier" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The identifier of the metadata document that was QCed.
This is optional since in some cases, we will be performing 
QC on objects that are being actively edited/created and 
do not yet exist with persistent identifiers.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="metadata" type="tns:metadata">
<xs:annotation>
<xs:documentation><![CDATA[Additional information about the document that was QCed.
This can be helpful when analyzing and aggregating batches of run results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="suiteId" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The identifier for the suite that was run]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="result" type="tns:result">
<xs:annotation>
<xs:documentation><![CDATA[The list of results for this run. Results contain the check that was run and 
the outcome of the check.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="suite">
    <xs:sequence>
      <xs:element name="id" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[The unique identifier for the suite. This should be unique, at the very least, 
within the scope of the MDQ engine store. It will be used to identify which
suite[s] to run on metadata documents and for organizing QC results.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element name="name" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[A short and useful name for the suite that will be displayed in 
user interfaces and reports.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element minOccurs="0" name="description" type="xs:string">
<xs:annotation>
<xs:documentation><![CDATA[A comprehensive sumary of the suite and what it is intended to check.]]></xs:documentation>
</xs:annotation>
</xs:element>
      <xs:element maxOccurs="unbounded" name="check" type="tns:check">
<xs:annotation>
<xs:documentation><![CDATA[The list of checks to be performed. A suite must have at least one check.]]></xs:documentation>
</xs:annotation>
</xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="level">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="OPTIONAL"/>
      <xs:enumeration value="REQUIRED"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="SUCCESS"/>
      <xs:enumeration value="FAILURE"/>
      <xs:enumeration value="SKIP"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== NCEAS/mdqengine/src/main/resources/checks/contact.has.orcid.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 ../schemas/schema1.xsd">
	<id>check.contact.has.orcid.1</id>
	<name>Contact information with ORCID</name>
	<description>Contact should contain an ORCID, email, and address.</description>
	<type>identification</type>
	<level>INFO</level>
	<environment>rscript</environment>
	<code><![CDATA[
  check <- function() {
    # These variables are defined by the MQE from the <xpath> selectors.
    # "contactPresent" - is the dataset contact present
    # "userId"         - the dataset contact/userId
    # "emailPresent"   - the contact email
    # "addressPresent" - the contact address

    if (!contactPresent) {
      return(list(status = "FAILURE",
                  output = "A contact is not present, so unable to check for an ORCID, email, or address."))
    }

    # Assume that the check will succeed, until proven otherwise
    status <- "SUCCESS"
    # The output messages will be gathered into a list
    values <- list()

    # There could be multiple contacts, but just one contact with a 'userId' will satisfy this check
    if (is.null(userId)) {
      # Should this be a SKIP?
      status <- "FAILURE"
      values[[length(values) + 1]] <- list(value = "A user identifier for any contact is not present, so unable to check for an ORCID.")
    } else {
      # contact/userId is present, so check if it is an ORCID
      hasORCID <- grepl("^\\s*http(s)?://(dx\\.)?doi\\.org/(doi:)?10\\..+", userId, perl = TRUE) || grepl("^\\s*doi:10\\..+", userId, perl = TRUE)
      if (hasORCID) {
        values[[length(values) + 1]] <- list(value = "The user identifier for a contact is an ORCID.")
      } else {
        status <- "FAILURE"
        values[[length(values) + 1]] <- list(value = "The user identifier for any contact is not an ORCID.")
      }
    }

    # There could be multiple contacts, but just one contact with an 'email' will satisfy this check
    if (emailPresent) {
      values[[length(values) + 1]] <- list(value = "An email address for a contact is present.")
    } else {
      status <- "FAILURE"
      values[[length(values) + 1]] <- list(value = "An email address for any contact is not present.")
    }

    # There could be multiple contacts, but just one contact with an 'address' will satisfy this check
    if (addressPresent) {
      values[[length(values) + 1]] <- list(value = "An address for a contact is present.")
    } else {
      status <- "FAILURE"
      values[[length(values) + 1]] <- list(value = "An address for any contact is not present.")
    }

    return(list(status = status,
                values = values))
  }

  result <- check()

  mdq_result <- list(status = result$status,
                     output = result$values)
  ]]></code>
  <selector>
		 <name>contactPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/contact)</xpath>
	 </selector>
  <selector>
		 <name>userId</name>
		 <xpath>/*[local-name() = 'eml']/dataset/contact/userId</xpath>
	 </selector>
  <selector>
		 <name>emailPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/contact/electronicMailAddress)</xpath>
	 </selector>
  <selector>
		 <name>addressPresent</name>
		 <xpath>boolean(/*[local-name() = 'eml']/dataset/contact/address)</xpath>
	 </selector>
	 <dialect>
		 <name>eml</name>
		 <xpath>boolean(/*[local-name() = 'eml'])</xpath>
	 </dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/nsf.award.number.present.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
	<id>check.nsf.award.numbers.present.1</id>
	<name>NSF award numbers</name>
	<description>One or more NSF award numbers must be entered.
	</description>
	<type>identification</type>
	<level>REQUIRED</level>
	<environment>rscript</environment>
	<code><![CDATA[
if (is.null(awards)) {
  status <- "FAILURE"
  output <- "No award numbers were found."
  mdq_result <- list(status = status,
                     output = list(list(value = output)))
} else if (length(title) < 1) {
  status <- "FAILURE"
  output <- paste0(length(title), " award number(s) found when at least one was expected.")
  mdq_result <- list(status = status,
                     output = list(list(value = output)))
} else if (any(nchar(awards) <= 0)) {
  status <- "FAILURE"
  output <- paste0("The following award numbers were of zero length: ", which(nchar(awards) <= 0, "."))
  mdq_result <- list(status = status,
                     output = list(list(value = output)))
} else {
  status <- "SUCCESS"
  output <- ""
  if(length(output) > 1) {
    output <- paste0("These ", length(awards), " NSF award numbers were found: ", sQuote(unlist(awards)))
  } else {
    output <- paste0("This single NSF award number was found: ", sQuote(unlist(awards)))
  }
  mdq_result <- list(status = status,
                     output = list(list(value = output)))
}]]></code>
	<selector>
		<name>awards</name>
		<xpath>/eml/dataset/project/funding/para</xpath>
	</selector>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nceas.ucsb.edu/mdqe /Users/leinfelder/git/mdqengine/src/main/resources/schemas/schema1.xsd">
  <id>contact</id>
  <name>Contact is present</name>
  <level>REQUIRED</level>
  <environment>rscript</environment>  
  <code>
    library(metadig)
    check_presence(contact)
  </code>
  <selector>
    <name>contact</name>
    <xpath>/eml/dataset/contact</xpath>
  </selector>
  <dialect>
    <name>eml</name>
    <xpath>boolean(/*[local-name() = 'eml'])</xpath>
  </dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/methods.present.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
	<id>check.methods.present.1</id>
	<name>Methods present</name>
	<description>All datasets should contain a methods element, at a minimum a link to a separate methods doc.</description>
	<type>interpretation</type>
	<level>OPTIONAL</level>
	<environment>rscript</environment>
	<code><![CDATA[
check <- function() {
    # Check that a <methods> element is present for the dataset.
    if(methodsPresent) {
        status <- "SUCCESS"
        output <- "A methods element is present"
    } else {
        status <- "FAILURE"
        output <- "A methods element is not present"
    }
    mdq_result <- list(status=status, output=list(list(value=output)))
    return (mdq_result)
}

mdq_result <- check()
      ]]></code>
	<selector>
		<name>methodsPresent</name>
		<xpath>boolean(/*[local-name() = 'eml']/dataset/methods)</xpath>
	</selector>
	<dialect>
		<name>eml</name>
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialect>
</mdq:check>

=== NCEAS/mdqengine/src/main/resources/checks/entity.name.present.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
	<id>check.entity.name.present.1</id>
	<name>Check that an entity name, description, format, size, checksum is present</name>
	<description>Check that each data entity has a name, description, format, size, checksum.</description>
	<type>interpretation</type>
	<level>REQUIRED</level>
	<environment>rscript</environment>
	<code><![CDATA[

check <- function() {
  library(base)
  library(metadig)
  # varialbe defined by MQE from the <xpath> selectors.
  # "entityName" - the names of each data entity
  # "entityDescriptionPresent" - is the names of each data entity present
  # "entityFormatPresent" - is the description for the entity present
  # "entitySizePresent" - is the description for the entity present
  # 'entityChecksumPresent" - is the checksum value (e.g. SHA1, MD5) of the entity present
  
  outputList <- list()
  # Assume that the check will succeed, until proven otherwise.
  # The dataset may have multiple entities, so check each one. All entities are checked
  # so mdqe can report to the user about all entities, not just the one that failed.
  # Set quote style to simple quotes
  skip <- FALSE
  if (length(entityName) > 0) {
    for(iEntity in 1:length(entityName)) {
      # Assume that the check will succeed, until proven otherwise.
      undefEl <- list()
      thisEntityType <- entityType[[iEntity]]
      
      if(!isDefined("entityName", entityName, iEntity)) {
        undefEl[[length(undefEl)+1]] <- "name"
        thisEntityName <- sprintf("%d", iEntity)
      } else {
        thisEntityName <- sprintf("%s", entityName[[iEntity]])
      }
      
      if(!isTrueVal("entityFormatPresent", entityFormatPresent, iEntity)) {
        undefEl[[length(undefEl)+1]] <- "format"
      }

      if(!isTrueVal("entitySizePresent", entitySizePresent, iEntity)) {
        undefEl[[length(undefEl)+1]] <- "size"
      }

      if(!isTrueVal("entityDescriptionPresent", entityDescriptionPresent, iEntity)) {
        undefEl[[length(undefEl)+1]] <- "description"
      }

      if(!isTrueVal("entityChecksumPresent", entityChecksumPresent, iEntity)) {
        undefEl[[length(undefEl)+1]] <- "checksum (authentication)"
      }

      # Store output for this entity if it didn't pass a check. We will only report on entities that don't have
      # all the elements we are checking for.
      if(length(undefEl) > 0) {
        outputList[[length(outputList)+1]] <- list(value=sprintf("Description for '%s' is missing these items: %s", thisEntityName, paste(sQuote(unlist(undefEl)), collapse=", ")))
      }
    }
  } else {
      # No data entities were selected by the xpath, so tell the user no check was performed and set status to SKIP
      outputList[[length(outputList)+1]] <- list(value=sprintf("No data descriptions are present, so unable to check entity 'name', 'format', etc"))
      skip <- TRUE
  }
  
  # If nt output was set, then the check passed, otherwise have to check for SKIP or FAILURE
  if(length(outputList) > 0) {
    if(skip) status <- "SKIP" else status <- "FAILURE"
    return(list(status=status, values=outputList))
  } else {
    return(list(status="SUCCESS", values=list(value=sprintf("All data description sections have a name, description, format, size and checksum"))))
  }
}

result <- check()
mdq_result <- list(status=result$status, output=result$values) 
]]></code>

	<!-- Don't need a subSelector for entityName, as this element is required, 
		so their won't be entities that are selected that don't have this value, 
		and therefor no 'blank' values. -->
	<selector>
		<name>entityName</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]/entityName</xpath>
	</selector>
	<selector>
		<name>entityType</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]</xpath>
		<subSelector>
		<name>et</name>
		<xpath>name(.)</xpath>
		</subSelector>
	</selector>
	<selector>
		<name>entityDescriptionPresent</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]</xpath>
		<subSelector>
			<name>entityDescriptionSubSelector</name>
			<xpath>boolean(./entityDescription)</xpath>
		</subSelector>
	</selector>
	<selector>
		<name>entitySizePresent</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]</xpath>
		<subSelector>
			<name>entitySizeSubSelector</name>
			<xpath>boolean(./physical/size)</xpath>
		</subSelector>
	</selector>
	<selector>
		<name>entityFormatPresent</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]</xpath>
		<subSelector>
			<name>entityFormatPresentSubSelector</name>
			<xpath>boolean(./physical/dataFormat)</xpath>
		</subSelector>
	</selector>
	<selector>
		<name>entityChecksumPresent</name>
		<xpath>/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]</xpath>
		<subSelector>
			<name>entityChecksumPresentSubSelector</name>
			<xpath>boolean(./physical/authentication)</xpath>
		</subSelector>
	</selector>
	<dialect>
		<name>eml</name>
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialect>
</mdq:check>
